### ISSUE TITLE
Severity	Code	Description	Project	FiThe type or namespace name 'AxACTIVEHAPTEKX1Lib' could not be found (are you missing a using directive or an assembly reference)

### ISSUE THREAD

**Issue by parth-khant** [KidRolex/AiChatBot#1]
i'm having 3 errors mate.

Error1: The type or namespace name 'AxACTIVEHAPTEKX1Lib' could not be found (are you missing a using directive or an assembly reference?)	

Error2: CS0246	The type or namespace name 'AxACTIVEHAPTEKXLib' could not be found (are you missing a using directive or an assembly reference?)	

i'm having this upper errors in Form1,Designer.cs file.

i think these errors are occuring because of this>>
            ..................................................................
            this.Name = "Form1";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.Form1_Load);
            ((System.ComponentModel.ISupportInitialize)(this.axActiveHaptekX1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
            .........................................................
        }
     THERE IS SOMETHING WRONG WITH 4TH LINE,,
CAN YOU PLEASE JUST HELP ME??

**Comment by zeroplus4** [comment]
brother please am encounting an error on sigploit and i saw how you resolved your issue..

please can you help out

my email is                      ravynclark@protonmail.com
